### ISSUE TITLE
Magic numbers in prefix code

### ISSUE THREAD

**Issue by codetsunami** [xrp-community/xrpl-tagged-address-codec#2]
https://github.com/xrp-community/xrpl-tagged-address-codec/blob/031e57f8c0bb6cd2ea514baafadf45075b3541b5/src/utils/index.ts#L34

This at minimum needs a commenting to explain why each of these calculations are done.

(My gut says ceil(chars + 0.2) here is likely wrong and will break for some specific edge case.)

**Comment by codetsunami** [comment]
Looking further, these calculations are unnecessary, as the payload will always be exactly 30 bytes and the base will always be 58

**Comment by WietseWind** [comment]
@codetsunami Must admit: don't know. Used some of the code from over here: https://github.com/ripple/x-address-codec/blob/master/src/address-codec.js#L145
